version: '3.8'

services:
  app:
    build:
      context: ./node
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    networks:
      - default-network
    depends_on: 
      - db    

  db:
    image: mysql:5.7               
    command: --innodb-use-native-aio=0    
    restart: always
    tty: true
    networks:
      - default-network
    volumes:
      - ./mysql:/var/lib/mysql
      - ./node/.docker/mysql:/docker-entrypoint-initdb.d
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=password      

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - default-network
    depends_on:
      - app

networks:
  default-network:
    driver: bridge